apiVersion: v1
kind: Secret
metadata:
  name: {{ include "esp.fullname" . }}-db
  labels:
    {{- include "esp.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else if .Values.externalDatabase.existingSecret }}
  {{/* Use existing secret */}}
  {{- else }}
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "esp.fullname" . }}-jwt
  labels:
    {{- include "esp.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.config.api.jwt_secret | default (randAlphaNum 64) | b64enc | quote }}
