apiVersion: v1
kind: Service
metadata:
  name: {{ include "esp.fullname" . }}
  labels:
    {{- include "esp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.smtp }}
      targetPort: smtp
      protocol: TCP
      name: smtp
    - port: {{ .Values.service.ports.smtps }}
      targetPort: smtps
      protocol: TCP
      name: smtps
    - port: {{ .Values.service.ports.submission }}
      targetPort: submission
      protocol: TCP
      name: submission
    - port: {{ .Values.service.ports.imap }}
      targetPort: imap
      protocol: TCP
      name: imap
    - port: {{ .Values.service.ports.imaps }}
      targetPort: imaps
      protocol: TCP
      name: imaps
    - port: {{ .Values.service.ports.api }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "esp.selectorLabels" . | nindent 4 }}
